### ISSUE TITLE
Running Instructions

### ISSUE THREAD

**Issue by waynemaranga** [readsoftware/read#7]
For ease of use, please include brief running instructions on ReadMe.

**Comment by stevewh** [comment]
You can find Cloud install instructions in the maindev2 branch that are from Feb 2019 in the original private repro. Note they need some updating. Also checkout the docker directory for a Docker development setup (also on the maindev2 branch).

**Comment by waynemaranga** [comment]
Managed to set it up with Docker. Thanks!

**Comment by stevewh** [comment]
Hi Wayne,
  What are you thinking to do with READ ?
Cheers

**Comment by waynemaranga** [comment]
Hey
I want to set it up and go through it in my free time to see exactly (or almost exactly) how it works. Just curious 😄
